# Setup
title:               'Thomas Treillard'
tagline:             ''
description:         ''
url:                 https://toma-x.github.io/
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Thomas Treillard
  url:               https://toma-x.github.io/
  email:             thomas.treillard@dauphine.eu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
